apiVersion: v1
kind: ServiceAccount
metadata:
  name: faiq-tester
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faiq-tester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: faiq-tester
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: faiq-kudo-test
spec:
  serviceAccountName: faiq-tester
  containers:
    - name: faiq-kudo-test
      image: faiq/kudo-example
      command: ["kubectl", "kudo", "test","--config", "./kudo-test.yaml"]
